name: Testing all Hosts

# Trigger the workflow on pushes to main and any pull request
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:


  # -----------------------------------------------------------------
  # Testing Modules -> PythonLib
  # -----------------------------------------------------------------
  test_modules_pythonlib:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
          submodules: true

    - name: Install System Python and Bluetooth Headers
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-dev python3-pip

    - name: Install Python Tools
      run: |
        pip install pylint
        pip install black

    - name: Check Wifi
      working-directory: ./modules/pythonlib
      run: make check-wifi

    - name: Prepare Bluetooth
      run: |
        sudo apt-get update
        sudo apt-get install -y libbluetooth-dev

    - name: Check Bluetooth
      working-directory: ./modules/pythonlib
      run: make check-bluetooth

    - name: Prepare BLE
      working-directory: ./modules/pythonlib
      run: pip install -r requirements-ble.txt

    - name: Check BLE
      working-directory: ./modules/pythonlib
      run: make check-ble
