name: Testing all Hosts

# Trigger the workflow on pushes to main and any pull request
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:


  # -----------------------------------------------------------------
  # Testing Modules -> PythonLib
  # -----------------------------------------------------------------
  modules-pythonlib:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
          submodules: true

    - name: Install System Python and Bluetooth Headers
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-dev python3-pip

    - name: Install Python Tools
      run: |
        pip install pylint
        pip install black

    - name: Check Wifi
      working-directory: ./modules/pythonlib
      run: make check-wifi

    - name: Prepare Bluetooth
      run: |
        sudo apt-get update
        sudo apt-get install -y libbluetooth-dev

    - name: Check Bluetooth
      working-directory: ./modules/pythonlib
      run: make check-bluetooth

    - name: Prepare BLE
      working-directory: ./modules/pythonlib
      run: pip install -r requirements-ble.txt

    - name: Check BLE
      working-directory: ./modules/pythonlib
      run: make check-ble

  # -----------------------------------------------------------------
  # Testing Modules -> CppLib
  # -----------------------------------------------------------------
  modules-cpplib:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
          submodules: true

    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install -y build-essential clang-format

    - name: Run clang-format
      working-directory: ./modules/cpplib
      run: |
        clang-format --dry-run --Werror $(find src -name '*.cpp' -o -name '*.h')

    - name: Run C++ Tests
      working-directory: ./modules/cpplib
      run: |
        make build-lib
        make build-host 

  # -----------------------------------------------------------------
  # Testing Android -> Sample Bodynodes Host App
  # -----------------------------------------------------------------
  android-samplebodynodeshost:
    name: Build and Test Sample Bodynodes Host App
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [35]
        target: [google_apis]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            submodules: true

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      # Enable caching
      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3
        
      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          system-image-api-level: ${{ matrix.system-image-api-level }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Run emulator and tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          system-image-api-level: ${{ matrix.system-image-api-level }}
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          working-directory: ./android/SampleBodynodesHost
          script: |
            ./gradlew assembleDebug
            ./gradlew connectedDebugAndroidTest --info --stacktrace

  # -----------------------------------------------------------------
  # Testing PC -> Blender scripts
  # -----------------------------------------------------------------
  pc-blender:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
          submodules: true

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.X'

    - name: Install Python Tools
      run: |
        pip install pylint
        pip install black
        pip install fake-bpy-module-5.0

    - name: Check Blender scritps
      working-directory: ./pc/blender
      run: make check-all

  # -----------------------------------------------------------------
  # Testing PC -> Robotic Arm ZYY scripts
  # -----------------------------------------------------------------
  pc-robotic-arm-zyy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
          submodules: true

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.X'

    - name: Install Python Tools
      run: |
        pip install -r pc/robotic_arm_zyy/real_robotic_arm_zyy/requirements.txt
        pip install -r pc/robotic_arm_zyy/virtual3d_robotic_arm_zyy/requirements.txt
        pip install -r pc/robotic_arm_zyy/virtual3d_sensors/requirements.txt

    - name: Check robot scritps
      working-directory: ./pc/robotic_arm_zyy
      run: make check-all

